name: Build and Deploy to VPS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package

    - name: Build Docker image
      run: docker build -t consitech-lm-backend .

    - name: Run new container on a different port for testing
      run: |
        docker run -d --name consitech-lm-backend-test -p 8081:8080 consitech-lm-backend

    - name: Health check
      run: |
        RETRIES=5
        until curl --silent --fail http://localhost:8081 || [ $RETRIES -eq 0 ]; do
          echo "Waiting for container..."
          sleep 10
          RETRIES=$((RETRIES - 1))
        done
        if [ $RETRIES -eq 0 ]; then
          echo "New container failed to start"
          docker logs consitech-lm-backend-test
          docker rm -f consitech-lm-backend-test
          exit 1
        fi

    - name: Stop and remove old container
      run: docker rm -f consitech-lm-backend || true

    - name: Start new container on the original port
      run: |
        docker rm -f consitech-lm-backend-test
        docker run -d --name consitech-lm-backend -p 8080:8080 consitech-lm-backend
