name: DEV Build and Deploy to VPS

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t consitech-lms-backend-dev .

      - name: Stop and remove old container
        run: docker rm -f consitech-lms-backend-dev-container || true

      - name: Start new container
        run: |
          docker run -d --name consitech-lms-backend-dev-container \
            -p 8082:8080 \
            --network dev-network \
            --restart unless-stopped \
            -e SERVER_PORT=${{ secrets.SERVER_PORT_DEV }} \
            -e DB_URL=${{ secrets.DB_URL_DEV }} \
            -e DB_USER=${{ secrets.DB_USER_DEV }} \
            -e DB_PASS=${{ secrets.DB_PASS_DEV }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e SMTP_HOST=${{ secrets.SMTP_HOST }} \
            -e SMTP_PORT=${{ secrets.SMTP_PORT }} \
            -e SMTP_USERNAME=${{ secrets.SMTP_USERNAME }} \
            -e SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }} \
            -e ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }} \
            -e ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }} \
            -e ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }} \
            -e CLOUDINARY_NAME=${{ secrets.CLOUDINARY_NAME }} \
            -e CLOUDINARY_KEY=${{ secrets.CLOUDINARY_KEY }} \
            -e CLOUDINARY_SECRET=${{ secrets.CLOUDINARY_SECRET }} \
            consitech-lms-backend-dev
